### ISSUE TITLE
ExtractBinding indentation conflicts with case alternatives

### ISSUE THREAD

**Issue by kelemzol** [haskell-tools/haskell-tools#176]
```
nok x = case x of
  (Just i) -> i * i
  Nothing -> 0
```

ExtractBinding on "i * i"
result:

```
module Demo where
nok x = case x of
  (Just i) -> ex
  Nothing -> 0
  where ex = i * i
```

**Comment by nboldi** [comment]
One expected result could be:

```
module Demo where

nok x = case x of
  (Just i) -> x
    where x = i * i
  Nothing -> 0
```

Another is:
```
module Demo where

nok x = case x of
  (Just i) -> f i
  Nothing -> 0
 where f i = i * i
```

But in this case the indentation must be smaller than the indentation of the case alts and greater than the indentation of nok.

**Comment by nboldi** [comment]
See #143

**Comment by nboldi** [comment]
In some cases when the indentations are weird, we cannot even add the where clause. For example, if the case alternatives are indented one space from the body, there is no possible indentation for local definitions.

**Comment by nboldi** [comment]
In these cases we must re-indent the body of the definition. A formatter would indent the case alternatives to two space from the case itself, but I think here we should respect the original formatting and just ensure, that everything is at least indented at 4 spaces from the base definition.

**Comment by nboldi** [comment]
Only need to change when the actual element is an element of an indented list (do stmt, case alt, let def ...)
