### ISSUE TITLE
Where and let keywords remain after inlining the only binding in them

### ISSUE THREAD

**Issue by kelemzol** [haskell-tools/haskell-tools#177]
see the folowin code:

f a b = let x  = a + b in x * 2

The result  of InlineBinding on 'x' is an empty let. Its technicly correct, but i think should be considered that remove the let construction in this case.

**Comment by nboldi** [comment]
This problem is related to the empty where problem for inline binding, and will be solved by introducing classy plates.

**Comment by nboldi** [comment]
Or rather by doing a top-down traversal.

**Comment by zjhmale** [comment]
Hi @nboldi, is this fixed? I think I can still encounter this issue #209 in the online demo.

**Comment by nboldi** [comment]
Hi, yes it is fixed in the last release (0.5.0), but you are right, the online demo is not yet updated.

**Comment by zjhmale** [comment]
Cool, I will try it on my local machine then 😄 
>Hi, yes it is fixed in the last release (0.5.0), but you are right, the online demo is not yet updated.

**Comment by nboldi** [comment]
I also updated the demo. Have fun experimenting :+1:

**Comment by zjhmale** [comment]
Great! Thanks again :)
