### ISSUE TITLE
GenerateSignature for bindings with complex left-hand-side

### ISSUE THREAD

**Issue by kelemzol** [haskell-tools/haskell-tools#179]
Generate type signate doesnt working with boundings in patterns (in where/let)
for example:
```
f = a
  where
    (Just a) = Just 3
```
GenerateSignature on "`a`" in "`(Just a) = Just 3`"

**Comment by kelemzol** [comment]
The excepted result in this case the folowing:
```
f = a
  where
    a :: Integer
    (Just a) = Just 3
```

**Comment by nboldi** [comment]
In the first round, non-variable or function bindings could be disabled to prevent the exceptions. In the long run we have to think about when do we want to generate for example, multiple type signatures for 

```
(a,b) = (1,2)
```
