### ISSUE TITLE
Cannot satisfy <package>

### ISSUE THREAD

**Issue by zjhmale** [haskell-tools/haskell-tools#208]
I held a stack based project which with `QuickCheck` dependence, and after I ran

```
ht-refact ./ -one-shot -module-name=xxx -refactoring=GenerateExports
```

It will produce the error that

```
ht-refact: <command line>: cannot satisfy QuickCheck
    (use -v for more information)
```

After struggling with this for a while, I find if I use `cabal install QuickCheck` to install `QuickCheck` globally and make sure it will be a `QuickCheck` conf file in `~/.ghc/x86_64-darwin-8.0.1/package.conf.d`, I can kindly use this tool to refactor my Haskell files.

![image](https://cloud.githubusercontent.com/assets/6234553/21456833/e8d82098-c965-11e6-849c-099ea45db420.png)

But this is really wired, right? Should this tool check the package conf list locally from somewhere inside the `.stack-work` directory instead of scanning globally? Or am I missing something here?

Thanks in advance!

**Comment by nboldi** [comment]
ht-refact works like ghc, and it supports most of its flags. So, as for ghc, the default behavior is to look for packages in the global package repository. To override it, you should use the `-package-db` flag like `-package-db=.stack-work\...\pkgdb`
Even using `stack exec ht-refact ...` may help if stack exec correctly modifies the ghc path variable.

**Comment by zjhmale** [comment]
@nboldi Many thanks! `stack exec` will set the right local pkgdb path.
