### ISSUE TITLE
Redundant where keyword after inline binding

### ISSUE THREAD

**Issue by zjhmale** [haskell-tools/haskell-tools#209]
Currently, after I use `inline binding` refactoring in where bindings, it will leave a redundant `where` keyword which users have to delete it manually, so is this an unresolved issue or designed by goal?

Thanks in advance.

![screenshot](https://cloud.githubusercontent.com/assets/6234553/21490302/dc60dbdc-cc2d-11e6-80ee-229b761e70f4.gif)

**Comment by nboldi** [comment]
This is a low priority issue, and is already scheduled: #177
