### ISSUE TITLE
haskell-tools on Stackage

### ISSUE THREAD

**Issue by zjhmale** [haskell-tools/haskell-tools#210]
Using `stack install` or `cabal install` globally may run into some incompatibility issues between package sets. `stack build` for each of package sets can avoid this kind of issues.

Currently, I believe this tool is quite mature and maybe it's time to put it on Stackage 😃

**Comment by nboldi** [comment]
Created a pull request: https://github.com/fpco/stackage/pull/2168

**Comment by zjhmale** [comment]
@nboldi Thanks!

**Comment by nboldi** [comment]
The changes from [our request](https://github.com/fpco/stackage/pull/2168) had been pulled, so the haskell-tools packages will be on stackage with the next snapshot.

**Comment by zjhmale** [comment]
@nboldi Many thanks! Thus I can integrate this greate tool into [intellij-haskell](https://github.com/rikvdkleij/intellij-haskell/pull/94) ASAP 😄

**Comment by clojj** [comment]
nice!

**Comment by zjhmale** [comment]
Hi @nboldi, currently `haskell-tools` is already on Stackage [nightly](https://www.stackage.org/nightly-2017-01-07/hoogle?q=haskell-tools), thanks! But the `haskell-tools-cli` module which I think is the most useful for integration into editors isn't there, I can see it in [your request](https://github.com/fpco/stackage/pull/2168/files), maybe we should wait for more snapshots?

**Comment by nboldi** [comment]
Hi, there are some testing problems, so some of the packages are disabled on stack. I will try to sort out the problems soon.

Its great that you plan to integrate the tool with your IDE. One student at our university is working on the sublime text integration of the tool for his batchelor thesis. The repository he is working on is here: https://github.com/vazuaai/haskell-tool-sublime. The project is in an early state, but I later you will find lot of help there.

Some suggestions: the `haskell-tools-daemon` package is intended for integration with editors. It receives commands through socket communication. The full protocol can be found here: https://github.com/haskell-tools/haskell-tools/blob/master/documentation/haskell-tools-refactoring-protocol.md

**Comment by zjhmale** [comment]
@nboldi Thanks for creating this amazing tool and accepting my request.
>Hi, there are some testing problems, so some of the packages are disabled on stack. I will try to sort out the problems soon.

Cool, this plugin will be inspiring 😄 
>Its great that you plan to integrate the tool with your IDE. One student at our university is working on the sublime text integration of the tool for his batchelor thesis. The repository he is working on is here: https://github.com/vazuaai/haskell-tool-sublime. The project is in an early state, but I later you will find lot of help there.

Yes, communicate with a daemon is a more common way to integrate a tool with editors indeed, thanks for the link, you helped me a lot 😄 
>Some suggestions: the haskell-tools-daemon package is intended for integration with editors. It receives commands through socket communication. The full protocol can be found here: https://github.com/haskell-tools/haskell-tools/blob/master/documentation/haskell-tools-refactoring-protocol.md

**Comment by nboldi** [comment]
Finally all of our packages are up on stackage: https://www.stackage.org/nightly-2017-01-14/hoogle?q=haskell-tools

Please close the ticket if you think the task is completed.

**Comment by zjhmale** [comment]
Yes, I can kindly use it with Stack now, Thanks for all the effort!
