### ISSUE TITLE
Stack install errors (trying to follow instructions in documentation/installation.md)

### ISSUE THREAD

**Issue by patrikja** [haskell-tools/haskell-tools#368]
Following the instructions in
  https://github.com/haskell-tools/haskell-tools/blob/master/documentation/installation.md
I get the following error:

patrikj@etyd:~$ stack install haskell-tools-daemon haskell-tools-cli
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading root                                                                                 
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Downloading mirrors                                                                              
Cannot update index (no local copy)                                                              
Downloading index                                                                                
Updated package list downloaded                                                                  
Populated index cache.                                                                           

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for haskell-tools-cli-0.6.0.0:
    haskell-tools-ast must match >=0.6 && <0.7, but the stack configuration has no specified version
                      (latest applicable is 0.6.0.0)
    haskell-tools-prettyprint must match >=0.6 && <0.7, but the stack configuration has no specified version
                              (latest applicable is 0.6.0.0)
    haskell-tools-refactor must match >=0.6 && <0.7, but the stack configuration has no specified version
                           (latest applicable is 0.6.0.0)
    references must match >=0.3 && <0.4, but the stack configuration has no specified version
               (latest applicable is 0.3.2.1)

In the dependencies for haskell-tools-daemon-0.6.0.0:
    aeson-0.11.2.1 must match >=1.0 && <1.2 (latest applicable is 1.1.1.0)
    haskell-tools-ast must match >=0.6 && <0.7, but the stack configuration has no specified version
                      (latest applicable is 0.6.0.0)
    haskell-tools-prettyprint must match >=0.6 && <0.7, but the stack configuration has no specified version
                              (latest applicable is 0.6.0.0)
    haskell-tools-refactor must match >=0.6 && <0.7, but the stack configuration has no specified version
                           (latest applicable is 0.6.0.0)
    references must match >=0.3.2 && <1.0, but the stack configuration has no specified version
               (latest applicable is 0.3.2.1)

Recommended action: try adding the following to your extra-deps in /home/patrikj/.stack/global-project/stack.yaml:
- haskell-tools-ast-0.6.0.0
- haskell-tools-prettyprint-0.6.0.0
- haskell-tools-refactor-0.6.0.0
- references-0.3.2.1

You may also want to try the 'stack solver' command
Plan construction failed.
patrikj@etyd:~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
patrikj@etyd:~$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0

**Comment by nboldi** [comment]
Currently the 0.6.0.0 version is only in a nightly stack release, so you need to set the snapshot with `--resolver`. The command `stack install haskell-tools-daemon-0.6.0.0 --resolver nightly-2017-04-05` works for me.

**Comment by nboldi** [comment]
I added the need to set the resolver in the documentation.
