### ISSUE TITLE
New GHC arrived almost 3 months ago - time for an update?

### ISSUE THREAD

**Issue by qrilka** [haskell-tools/haskell-tools#369]
From http://haskelltools.org/

> The tool is already on GHC 8.0.1 and will be updated immediately when a new GHC version arrives.

From https://www.haskell.org/ghc/

>11 Jan 2017
> GHC 8.0.2 Released!

**Comment by nboldi** [comment]
Yes, I have to update the webpage, since the tool is already on GHC 8.0.2
