### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by nrolland** [haskell-tools/haskell-tools#379]
Are there simple examples with the new API like you had for haskell exchange ?
(I just want to extract programmatically some types)

I noticed the API has changed, like `readSrcSpan` which gets its file name from somewhere else

**Comment by nboldi** [comment]
The updated tutorial have been migrated into the repository contents: https://github.com/haskell-tools/haskell-tools/blob/master/documentation/development/tutorials/dollar-app.md. The step-by-step refactorings are in the codebase (to keep them updated): https://github.com/haskell-tools/haskell-tools/tree/master/src/refactor/Language/Haskell/Tools/Refactor/Predefined

If you intend to extract types, I suggest to check the source code of the generate type signature refactoring: https://github.com/haskell-tools/haskell-tools/blob/master/src/refactor/Language/Haskell/Tools/Refactor/Predefined/GenerateTypeSignature.hs

Aside from the haskell exchange tutorial, we have two simple examples in the tutorial secion: https://github.com/haskell-tools/haskell-tools/blob/master/documentation/development/tutorials.md

**Comment by nrolland** [comment]
That's great doc !

May I suggest that you put a link to it on the README.md ?

I did not see spot it and then got lost in the tree
