### ISSUE TITLE
Does not work with `Paths_` module

### ISSUE THREAD

**Issue by rikvdkleij** [haskell-tools/haskell-tools#391]
If in cabal file module `Paths_[package name]` is added to `other-modules`, `ht-refact` gives this error in stdout:
```
Compiling modules. This may take some time. Please wait.
Source code problem: <no location info>: error:
    module ‘Paths_[package name]’ is a package module
```

Haskell-tools version 0.5.0.0

**Comment by rikvdkleij** [comment]
It would also be great if this kind of messages would go to stderr so it's clear when something goes wrong

**Comment by nboldi** [comment]
First of all: the `Paths_..` file should exist before you start refactoring. So you need to run `cabal build` or similar command.
If you use the ht-daemon executable (because you use the editor integration), it should automatically calculate the location of the `Paths_..` file.
If you use the ht-refact executable (the command-line refactoring tool), you should manually add the folder where the `Paths_..` file is generated. Eg. `[projectdir]/.../autogen`.

**Comment by rikvdkleij** [comment]
Thanks for your quick reply.

> First of all: the Paths_.. file should exist before you start refactoring. So you need to run cabal build or similar command.

I have run `stack build`.

> If you use the ht-refact executable (the command-line refactoring tool), you should manually add the folder where the Paths_.. file is generated. Eg. [projectdir]/.../autogen.

I did not know/read that I had to add `autogen` directory, only to add project directory which contains cabal file to `ht-refact`.


Maybe it's better to use `ht-daemon` inside IntelliJ integration. I will give that also a try.

**Comment by nboldi** [comment]
For creating the integration I would suggest using `ht-daemon`, as now it also handles the use of different package dbs. In the future, the functionality of `ht-daemon` and `ht-refact` will be similar.

**Comment by rikvdkleij** [comment]
> For creating the integration I would suggest using ht-daemon, as now it also handles the use of different package dbs.

Great!

I can find documentation about how to manage/call `ht-daemon`.

**Comment by nboldi** [comment]
To start the executable use `ht-daemon [port-number]` (default port number is 4123)

You can communicate with the executable using a socket connection (on the given port). The list of possible requests and responses can be found here: https://github.com/haskell-tools/haskell-tools/blob/master/documentation/development/haskell-tools-refactoring-protocol.md

**Comment by rikvdkleij** [comment]
Thanks! It's a cool project!
