### ISSUE TITLE
Generating type signature ignores name clash from new import

### ISSUE THREAD

**Issue by rikvdkleij** [haskell-tools/haskell-tools#423]
Example:
```haskell
module Foo where

import Protolude

makeLazy = fromStrict
```

Generating type signature for `makeLazy` gives:
```haskell
module Foo where

import Protolude
import Data.Text.Internal.Lazy(Text)

makeLazy :: Text -> Text
makeLazy = fromStrict
```
which does not compile.

Expected:
```
makeLazy :: Text -> LText
```
without importing
```
import Data.Text.Internal.Lazy(Text)

```

**Comment by nboldi** [comment]
I couldn't find the definition of `fromStrict` exported from `Protolude` [here](https://hackage.haskell.org/package/protolude-0.1.10/docs/Protolude.html)

**Comment by rikvdkleij** [comment]
You will have to look in the code. It reexports a lot of modules as X.

**Comment by nboldi** [comment]
Yes, haddock doesn't handle the reexport-as-X trick. I will look into whats going on.

**Comment by rikvdkleij** [comment]
Thanks!

Btw, how can I find out which version of `haskell-tools` is installed on the command line?

**Comment by nboldi** [comment]
There is no explicit version switch. Currently you can check it by checking the version of the package(s) you installed.

**Comment by nboldi** [comment]
Actually `LText` is just a type synonym for `Text`. It is not feasible to figure out which type synonym to use.
The compilation problem actually arises from missing the check for name collosion caused by the new import added.

The correct solution would be (`Z` is a new name):
```
module Foo where

import Protolude
import qualified Data.Text.Internal.Lazy as Z(Text)

makeLazy :: Text -> Z.Text
makeLazy = fromStrict
```

**Comment by nboldi** [comment]
Another possibility is to create a fully qualified name reference:
```haskell
module Foo where

import Protolude
import qualified Data.Text.Internal.Lazy(Text)

makeLazy :: Text -> Data.Text.Internal.Lazy.Text
makeLazy = fromStrict
```

**Comment by rikvdkleij** [comment]
GHC also derives `makeLazy :: Text -> Data.Text.Internal.Lazy.Text`.

I understand that it is not possible to figure out type alias so this seems to be the best solution (together with the qualified import).

**Comment by rikvdkleij** [comment]
Maybe I'm asking too much but in theory you could check if Protolude defines a type alias for this type.

**Comment by nboldi** [comment]
It would be great, but unfortunately I don't think we have the resources right now to do it. It needs some heuristics on which type synonym to use, and partially applied type synonyms should also be matched.

**Comment by nboldi** [comment]
Please check the referencing pull request.

**Comment by rikvdkleij** [comment]
Okay, I see, it's the most solid solution. If necessary, more refactoring can be done after this refactor.
