### ISSUE TITLE
OrganizeConstraints

### ISSUE THREAD

**Issue by kelemzol** [haskell-tools/haskell-tools#479]
Simplify and organize constraints.

# Remove the redundant constraints.
## Trivial
```
f :: (A a, A a) => a
```
->
```
f :: (A a) => a
```
## PreConstraints
```
class B a => A a where ...
f :: (A a, B a) => a
```
->
```
class B a => A a where ...
f :: (A a) => a
```
## InlineTrivial
```
type A a = (B a, C a)
f :: (A a, B a) => a
```
->
```
type A a = (B a, C a)
f :: (A a) => a
```
## Problems
* Constraint families

# Remove the unused constraints
example:
```
f :: (Num a, Show a) => a -> a
f = (*2)
```
->
```
f :: (Num a) => a -> a
f = (*2)
```

# Sorting by any aspect
### questions
* what logical aspect?
* local or global

**Comment by nboldi** [comment]
I moved this refactoring idea to a wiki page dedicated for refactoring ideas: https://github.com/haskell-tools/haskell-tools/wiki/OtherRefactorings#remove-the-redundant-constraints
