### ISSUE TITLE
When using tryRefactor, where should I put the input <moduleName>.hs file? (Exception: module ‘Test’ is a package module)

### ISSUE THREAD

**Issue by SnowOnion** [haskell-tools/haskell-tools#513]
Hello,

I'm trying [tutorials/data-to-newtype](documentation/development/tutorials/data-to-newtype.md). When I evaluated `tryItOut "Test"`, ghci gave `*** Exception: module ‘Test’ is a package module`. 
I thought maybe I put `Test.hs` to wrong place. Is that the reason? Where should I put `Test.hs`?

# Detail

I did the following steps:
1. Created an empty stack project, added `build-depends` in `try-haskell-tools-ast.cabal`:
```
  build-depends:       base >= 4.7 && < 5
                       ,haskell-tools-refactor
                       ,references
```
2. Copied [`DataToNewtype.hs`](src/experimental-refactorings/Language/Haskell/Tools/Refactor/Builtin/DataToNewtype.hs) to my `src/DataToNewtype.hs`, renamed the module name from `Language.Haskell.Tools.Refactor.Builtin.DataToNewtype` to `DataToNewtype`, and set `exposed-modules:     DataToNewtype` in `try-haskell-tools-ast.cabal`.
3. Created `src/Test.hs` with content:
```
module Test where
data A = A Int
```
then the project tree became
```
➜  try-haskell-tools-ast tree
.
├── LICENSE
├── README.md
├── Setup.hs
├── app
│   └── Main.hs
├── src
│   ├── DataToNewtype.hs
│   └── Test.hs
├── stack.yaml
├── test
│   └── Spec.hs
└── try-haskell-tools-ast.cabal
```
4. Executed `stack ghci`, evaluated `tryItOut "Test"`, and it gave:
```
*Main DataToNewtype> tryItOut "Test"
*** Exception: module ‘Test’ is a package module
```

Thanks!

**Comment by nboldi** [comment]
I think the working directory is the root of the package by default, so the Test.hs file should go there.

**Comment by SnowOnion** [comment]
@nboldi Thank you. It works!😂
```
➜  try-haskell-tools-ast tree
.
├── Test.hs
├── src
│   └── DataToNewtype.hs
```

**Comment by nboldi** [comment]
@SnowOnion Great! If its working for you please close the issue.
