### ISSUE TITLE
Incorrect LANGUAGE pragma parse

### ISSUE THREAD

**Issue by Anabra** [haskell-tools/haskell-tools#585]
https://github.com/haskell-tools/haskell-tools/blob/e78c8f2ce199a4c7918973b91afd469112ec74a3/src/backend-ghc/Language/Haskell/Tools/BackendGHC/Modules.hs#L128

Consider the following language pragma (with the respective indentation):

{-# LANGUAGE ViewPatterns
, ScopedTypeVariables
,RankNTypes
StandaloneDeriving,
, FlexibleContexts
, TypeApplications, ConstraintKinds
,TypeFamilies,MultiWayIf
#-}

**Comment by nboldi** [comment]
I think this is resolved in the released version.

**Comment by Anabra** [comment]
Resolved in v1.0.
