### ISSUE TITLE
Feature Request: cabal support

### ISSUE THREAD

**Issue by Fresheyeball** [haskell-tools/haskell-tools#590]
It would be lovely if this tool chain worked without stack, as some of us don't use Stackage.

**Comment by nboldi** [comment]
You can install Haskell-tools using the following command: `cabal install haskell-tools-daemon haskell-tools-cli`, as described in the [Install Instructions](https://github.com/haskell-tools/haskell-tools/blob/master/documentation/installation.md). You can refactor cabal/stack/cabal-sandbox projects as well as projects consisting of a folder with source files. If you encounter any trouble please let me know!

**Comment by nboldi** [comment]
I close this ticket due to inactivity.
