### ISSUE TITLE
FYI HaRe / ghc-exactprint

### ISSUE THREAD

**Issue by alanz** [haskell-tools/haskell-tools#73]
The wiki is not publicly editable.

The architecture page states that HaRe directly manipulates the token stream.

In fact, the recent versions (GHC 7.10 onwards) make use of API Annotations built into GHC and generate output via [ghc-exactprint] (https://github.com/alanz/ghc-exactprint)

**Comment by nboldi** [comment]
Thanks for the information. I based my assumptions on the earlier publications.

**Comment by nboldi** [comment]
By the way I changed the settings of the repository, so wiki pages should be freely editable by now.

**Comment by alanz** [comment]
Also, you should be hearing from @shayan-najd concerning his Haskell Summer of Code project which is also investigating the best way to modify the GHC AST to add annotations directly to it
